name: Godot CI

on:
  push:
    branches: [main]

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.2.2
        include-mono: false
    - run: godot --headless --quit 
